import {
  IconActivity,
  IconAlertCircle,
  IconArrowDown,
  IconArrowUp,
  IconAlertTriangle,
  IconBan,
  IconBrandTelegram,
  IconCheck,
  IconChecklist,
  IconChevronRight,
  IconCircleOff,
  IconCloudOff,
  IconCpu,
  IconClock,
  IconDeviceDesktop,
  IconDots,
  IconInbox,
  IconInfoCircle,
  IconLayoutDashboard,
  IconLock,
  IconLogout,
  IconMessages,
  IconMoon,
  IconPlus,
  IconRefresh,
  IconSearch,
  IconSettings,
  IconSparkles,
  IconSun,
  IconTrash,
  IconUnlink,
  IconUser,
  IconWifiOff,
  IconX,
  type TablerIcon,
} from "@tabler/icons-react";

const icons = {
  search: IconSearch,
  "alert-circle": IconAlertCircle,
  "alert-triangle": IconAlertTriangle,
  ban: IconBan,
  "brand-telegram": IconBrandTelegram,
  user: IconUser,
  clock: IconClock,
  "info-circle": IconInfoCircle,
  lock: IconLock,
  logout: IconLogout,
  "wifi-off": IconWifiOff,
  "cloud-off": IconCloudOff,
  refresh: IconRefresh,
  plus: IconPlus,
  trash: IconTrash,
  unlink: IconUnlink,
  check: IconCheck,
  "circle-off": IconCircleOff,
  "arrow-up": IconArrowUp,
  "arrow-down": IconArrowDown,
  sun: IconSun,
  moon: IconMoon,
  "device-desktop": IconDeviceDesktop,
  inbox: IconInbox,
  messages: IconMessages,
  sparkles: IconSparkles,
  activity: IconActivity,
  checklist: IconChecklist,
  settings: IconSettings,
  "layout-dashboard": IconLayoutDashboard,
  dots: IconDots,
  "chevron-right": IconChevronRight,
  cpu: IconCpu,
  x: IconX,
} satisfies Record<string, TablerIcon>;

export type IconName = keyof typeof icons;

export function Icon({ name, size = 24 }: { name: IconName; size?: number }) {
  const Component = icons[name];
  return <Component aria-hidden="true" size={size} stroke={1.5} />;
}
